name: Lint and Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-and-lint:
    uses: ./.github/workflows/common-node-setup.yml

  lint:
    needs: setup-and-lint
    runs-on: ubuntu-latest
    steps:
      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier check
        run: npm run format
